[build]
  command = "npm run build"
  functions = "src/functions"
  publish = "dist"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
